name: "CD Pipeline"

on:
    workflow_run:
        workflows: ["fastify-todo CI Pipeline / Workflow"]
        types:
            - completed
    

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: "Setup nodejs"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Setup vercel cli"
              run: npm install -g vercel

            - name: "Download build files"
              uses: actions/download-artifact@v4
              with:
                name: fastify-todo-build
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ github.token }}
            
            - name: Show downloaded files
              run: |
                pwd
                find .
            - name: "Deploy to vercel"
              run: vercel --prod --token=${{secrets.VERCEL_TOKEN }} --confirm --name=cicdfastifyproject

            - name: Health Check
              run: |
                curl -f https://your-app.vercel.app/health
